server:
  port: 8006
spring:
  application:
    name: consul-provider-payment
  #consul注册中心地址
  cloud:
    consul:
      host: 172.16.100.111
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true #打开心跳协议,否则会报错：No instances available for consul-provider-payment